name: Fetch PHP Versions

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  extract-php-versions:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.filter-versions.outputs.versions }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch and process PHP CLI tarballs
        id: filter-versions
        run: |
          versions="$(node dist/index.js discover --since-days 2)"

          if [ "$versions" = "[]" ]; then
            echo "No new PHP versions found to release."
          else
            echo "New PHP versions: $versions"
          fi

          echo "versions=$versions" >> $GITHUB_OUTPUT

  dispatch-releases:
    needs: extract-php-versions
    runs-on: ubuntu-latest
    if: needs.extract-php-versions.outputs.versions != '[]'
    strategy:
      matrix:
        version: ${{ fromJSON(needs.extract-php-versions.outputs.versions) }}
    permissions:
      contents: read
      actions: write
    steps:
      - name: Dispatch release workflow for PHP ${{ matrix.version }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: php-release.yml
          inputs: '{ "version": "${{ matrix.version }}" }'
